format = """
[](#3A3A3A)\
$os\
$username\
[](fg:#3A3A3A bg:#4A4A4A)\
$directory\
[](fg:#4A4A4A bg:#8C9440)\
$git_branch\
$git_status\
[](fg:#8C9440 bg:#5F819D)\
$docker_context\
$python\
[](fg:#5F819D bg:#3A5F5A)\
$time\
[](fg:#3A5F5A)\
$line_break$character"""

right_format = """$cmd_duration"""

command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

[os]
disabled = false
style = "bg:#3A3A3A"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#3A3A3A"
style_root = "bg:#3A3A3A"
format = '[ $user ]($style)'

[directory]
style = "bg:#4A4A4A"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#8C9440"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#5F819D"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = " "
style = "bg:#8C9440"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#8C9440"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#D4D4D4 bg:#8C9440"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#D4D4D4 bg:#8C9440"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#8C9440"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#8C9440"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#8C9440"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#8C9440"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#8C9440"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#8C9440"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#5F819D"
format = '[ $symbol( $version) \($virtualenv\) ]($style)'

[rust]
symbol = ""
style = "bg:#8C9440"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#3A5F5A"
format = '[  $time ]($style)'

[cmd_duration]
min_time = 10000
show_milliseconds = false
style = "bold #DE935F"
format = "[⏱ $duration]($style)"
